### ISSUE TITLE
Be able to associate a test (or tests) with a browser bug

### ISSUE THREAD

**Issue by jeffcarp** [web-platform-tests/results-collection#30] opened 2017-07-07 20:43 UTC
Via https://crbug.com/738440

It's important to be able to see if a browser knows about a given test failure.

**Comment by gsnedders** [comment] 2017-07-10 13:52
Ideally, there's some complexity needed here; Presto's old testing system ended up with multiple bugs attached to almost everything (some regressions that had slipped through in various ways, some regressions on specific feature branches, etc.) which meant that the signal:noise ratio was rubbish.

So:

 * We don't care about bugs long-since fixed.
 * We might care about bugs recently fixed (esp. if they're still in stable).
 * We care about bugs reopened after their fix has been reverted.
 * Some bugs may flip/flop (either because of unstable tests/browser bugs, and because nobody runs all of web-platform-tests and things might accidentally get fixed and then regressed).

That said, a simple dumb first implementation will probably initially suffice—all the real problems occur when the signal:noise decreases because of number of old bugs hanging around.

**Comment by alvestrand** [comment] 2018-02-14 10:49
would be ideal if we could enter bugs in a way that allows us to a) click on the entry to go to the bug, and b) run a script to update the state of all bugs so that fixed bugs disappear. But I'll settle for a hand-entered bug link in V1.

**Comment by foolip** [comment] 2018-02-14 11:38
@mariestaver do you have a label or milestone for things we should periodically revisit? This is a non-trivial feature, but one that I think will be in high demand once the dashboard is running pre-stable browsers daily or more often.

**Comment by mariestaver** [comment] 2018-02-15 18:51
@foolip I've repurposed the priority:backlog label for things to revisit while we make our quarterly plans, and will add the label to this issue.  Thanks!

**Comment by foolip** [comment] 2018-02-27 16:21
Some concrete cases where I'd have used this today:
* Link https://wpt.fyi/workers/interfaces/WorkerGlobalScope/onerror/propagate-to-window-onerror.html to https://bugs.chromium.org/p/chromium/issues/detail?id=590219 and https://github.com/whatwg/html/issues/1607
* Link failing subtests of https://wpt.fyi/fetch/data-urls/processing.any.html to https://bugs.chromium.org/p/chromium/issues/detail?id=807562 (and perhaps a more specific issue for https://github.com/w3c/web-platform-tests/pull/9693)

So I think it's not just browser bugs, being able to reference spec issues would also be useful.

**Comment by gsnedders** [comment] 2018-02-27 22:27
> So I think it's not just browser bugs, being able to reference spec issues would also be useful.

Also potentially test case bugs.

**Comment by foolip** [comment] 2018-04-17 10:35
Moved to https://github.com/web-platform-tests/wpt.fyi/issues/64.

**Closed by foolip** 2018-04-17 10:35 UTC
Labels: documentation, enhancement, priority:backlog
