### ISSUE TITLE
Test Edge Insider Preview

### ISSUE THREAD

**Issue by jeffcarp** [web-platform-tests/results-collection#109] opened 2017-08-31 17:37 UTC
This is available from [Browserstack](https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud) or it could be set up on a VM if possible.

**Comment by foolip** [comment] 2017-09-01 10:26
I can only see Edge 15 on BrowserStack, shouldn't the pre-release versions now be 16?

**Comment by jgraham** [comment] 2017-09-01 10:37
https://www.browserstack.com/list-of-browsers-and-platforms?product=live doesn't list any dev version for Edge.

Given that Edge preview releases are tied to Windows versions, I don't know any realistic alternative to running our own hardware here. With some effort you could probably script setting up a VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and use that to keep up to date with the latest available builds.

**Comment by foolip** [comment] 2017-09-01 11:34
FWIW, I did once try to install Windows Insider (not the Edge VMs) in VirtualBox and get it to upgrade to the most recent version, but never got it working. With a physical laptop I've succeeded, though.

**Comment by gsnedders** [comment] 2017-09-01 12:40
I feel like @thejohnjansen or @patrickkettner not say MS could potentially get us some reasonable way of having constantly up-to-date? From memory, trying to set up Insider builds for CI is virtually impossible because you need to leave the VM on for long enough to actually update (and presumably then save that state to create a new VM of the latest build), and it's very non-deterministic how long it takes before Windows Update even notices there's a new build (even if you literally tell it to repeatedly search for updates!).

**Comment by foolip** [comment] 2017-09-01 13:33
I don't know how much work this would require on @bobholt's side, but I think the setup would be roughly:
- Once a day, a URL like http://wpt.fyi/TEST_THESE_COMMITS is updated, so that everyone is testing using the same commit. (See https://github.com/GoogleChrome/wptdashboard/issues/40.)
- Microsoft runs the whole test suite, using the scripts checked into the web-platform-tests repo, or at least somewhere public so that it can be reproduced.
- Results are submitted to http://wpt.fyi/HERE_ARE_MY_RESULTS (with some auth thing) and show up on the dashboard.

**Comment by foolip** [comment] 2017-09-27 22:15
We've done some planning for Q4 now, and unfortunately this issue does not seem tractable right now. It's possible that BrowserStack or Sauce will get more recent versions of Edge, and there's been some discussion about Microsoft running tests and submitting builds. Neither of these seem imminent, so we'll revisit this for Q1.

@thejohnjansen @patrickkettner please shout loudly if this is not what you expected and we will do a 180!

**Comment by foolip** [comment] 2017-10-18 13:45
BrowserStack now also has Edge 16, which I think is now stable, but I'm not sure. In any case, Sauce Labs doesn't have it yet. Together with https://github.com/w3c/wptdashboard/issues/112#issuecomment-336623841 this suggests to me that BrowserStack is faster to offer new browser versions, and that we should look into using that instead. @mattl, can you look into what that might entail?

**Comment by patrickkettner** [comment] 2017-10-18 14:47
Edge 16 is stable as of yesterday. Browserstack also committed publically
to bringing insider builds to their platform in the near future ( I believe
before the end of the year, but I may be remembering that incorrectly).

I would also agree that it would be best to use them in this situation.

**Comment by foolip** [comment] 2017-10-18 17:48
That is amazing. If it's true, then we'd get everything we currently need except Safari TP, so going with BrowserStack seems like the way.

**Comment by jgraham** [comment] 2017-10-18 18:47
Do we know how that would affect our ability to run multiple concurrent test instances (e.g. for the sub-one-hour run time goal)?

**Comment by mattl** [comment] 2017-10-18 18:48
Looking at this now. It seems you can run multiple tests at the same time, you just pay more for the account. Up to 25 at time is listed, over that and you have to speak to them to get a quote.

**Comment by gsnedders** [comment] 2017-10-18 19:34
BrowserStack have previously offered to give us some stuff for free for wpt, though there may be limits as to how far we can go with that obviously!

**Comment by mukeshtiwari1987** [comment] 2017-10-24 15:17
@mattl and @gsnedders We have dropped you an email with details - Mukesh from BrowserStack Support.

**Comment by gsnedders** [comment] 2017-10-28 14:14
@mukeshtiwari1987 To what address? I can't find any email?

**Comment by mukeshtiwari1987** [comment] 2017-10-30 08:57
We have dropped email to: mattl(at)bocoup.com

**Comment by patrickkettner** [comment] 2018-03-22 14:42
@gsnedders @mattl was there an issue with getting browserstack setup? Edge Insider builds are supported so it would be great to test the version that has a years worth of improvements compared with sauce's

**Comment by foolip** [comment] 2018-03-22 15:05
Cool, Insider Preview now available, that must be very new, right?

@thejohnjansen is helping us look into the options here and I hope we'll resolve this issue one way or another before long.

**Comment by patrickkettner** [comment] 2018-03-22 15:07
> Cool, Insider Preview now available, that must be very new, right?
month or two, I believe

>@thejohnjansen is helping us look into the options here and I hope we'll resolve this issue one way or another before long.


👍

**Comment by foolip** [comment] 2018-03-26 12:17
@thejohnjansen @patrickkettner, how often is the Insider Preview on BrowserStack updated? Right now the UA string includes Edge/16.17025, but that's older than my laptop that I haven't updated in two months, 17.17063, and that laptop is now updating to 17127...

Using BrowserStack isn't plan A, but some idea about freshness would still be good.

**Comment by foolip** [comment] 2018-04-17 09:40
I just linked here from https://github.com/web-platform-tests/wpt.fyi/issues/60, but want to reiterate that Sauce or BrowserStack still aren't plan A, and that we're trying to work out a plan A involving VMs.

**Closed** 2019-01-27 22:19 UTC
Labels: project:runner, test-running
