### ISSUE TITLE
Dashboard counts failures and errors from the same test

### ISSUE THREAD

**Issue by RByers** [web-platform-tests/results-collection#191] opened 2017-11-03 14:05 UTC
From @AutomatedTester in https://github.com/w3c/web-platform-tests/issues/7979:

> if a test has an error AND a failure it is counted as two errors when a run has completed. this is obvious when you view https://wpt.fyi/webdriver/tests/actions.
> 
> chrome is erroring and failing so we get twice the failure numbers

@jeffcarp said:

> If both the test file and the only subtest returned anything other than PASS, it would be counted as 0/2 on the dashboard. You can see how this plays out where the denominator in a good majority of tests on wpt.fyi bottoms out at 2, not 1 - example: https://wpt.fyi/wasm

But I don't think that applies to the specific case @AutomatedTester points at.  There the test file is passing, but each sub-test is failing.  Related to #98 perhaps?

**Comment by jgraham** [comment] 2017-11-03 14:17
So this is sort of the opposite to the main thrust of #98. The main cause of that discrepancy is some test errors or not according to whether a feature is implemented, so in the passing case there are  more  subtests reported  and so more results.

In this case it  looks like when Chrome fails the tests those errors are double-counted compared to Firefox that  passes the tests. I couldn't reproduce a different  number of results using `wpt run` locally.

**Comment by jgraham** [comment] 2017-11-03 14:18
If you look at a detailed page like https://wpt.fyi/webdriver/tests/actions/key.py it shows the browsers running the same number of tests. So I think there's something wrong with the summarisation here.

**Comment by foolip** [comment] 2018-04-17 10:13
This is effectively a dupe of https://github.com/web-platform-tests/wpt.fyi/issues/62 if we're talking about tests where the subtest count isn't affected by implementation status.

**Closed by foolip** 2018-04-17 10:13 UTC
