### ISSUE TITLE
infrastructure/assumptions/ahem.html regressed in Firefox?

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/results-collection#610] opened 2018-09-28 15:33 UTC
https://wpt.fyi/results/infrastructure/assumptions/ahem.html seems to be failing in Firefox (stable and experimental) now.

**Comment by jugglinmike** [comment] 2018-09-28 23:16
Strange. May be related to [the switch to Ubuntu 18.04](https://github.com/web-platform-tests/results-collection/commit/c5dcfc317f51630ad182eef5f4f1d0947f80c023). Thanks for reporting!

**Comment by jugglinmike** [comment] 2018-09-29 02:04
[This project uses the WPT CLI's `--install-fonts` argument](https://github.com/web-platform-tests/results-collection/blob/d95e68e068bcd0cf9f4b395fd943dfab3872a24e/src/master/wpt_run_step.py#L98), so it's not a simple case of a missing file.

I can reproduce the failure outside of the build system by logging in to one of the machines and executing the following command:

    xvfb-run --auto-servernum ./wpt run --no-pause --no-manifest --no-headless firefox infrastructure/assumptions/ahem.html

For funsies, I also tried using Firefox's headless mode (which is now enabled by default):

    ./wpt run --no-pause --no-manifest firefox infrastructure/assumptions/ahem.html

This also fails.

I've manually installed the font and invoked `fc-cache` which every possible combination of `-f`, `-r`, and `~/.fonts`. The test fails in all cases.

But that's probably a dead end, anyway. Chrome passes the test in the presence of the WPT CLI's `--install-fonts` flag or if `~/.fonts/Ahem.ttf` is available (no need to invoke `fc-cache`), so I suspect this is a Firefox-specific problem.

[A very similar problem was reported by a web developer on the Ask Ubunutu forum about a month ago.](https://askubuntu.com/questions/1069613/firefox-only-uses-its-default-font-cant-use-any-others) Unfortunately, nothing came of that discussion. The author suggested that disabling the security sandbox may resolve the issue, but

    xvfb-run --auto-servernum ./wpt run --no-pause --no-manifest --no-headless \
       --setpref security.sandbox.content.level=0 \
       firefox infrastructure/assumptions/ahem.html

has no effect.

[Another forum thread references `gfx.font_rendering.cleartype_params.rendering_mode`](https://support.mozilla.org/en-US/questions/1115938), but setting that to `0` doesn't help, either:

    xvfb-run --auto-servernum ./wpt run --no-pause --no-manifest --no-headless \
      --setpref gfx.font_rendering.cleartype_params.rendering_mode=0 \
       firefox infrastructure/assumptions/ahem.html

I don't know what to try next, so I've filed a bug in BugZilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1495154

**Comment by jugglinmike** [comment] 2018-10-15 16:15
I was unable to reproduce this in Ubuntu 18.04 Server Edition (the version we're using in production), Ubuntu 18.04 Desktop Edition, or Ubuntu 16.04 Desktop Edition. I compared the fontconfig configuration files between the environments and found nothing of consequence. I installed all the system packages we install during provisioning, but that also had no effect. Fearing a regression in fontconfig itself (and lacking alternate installation candidates in apt), I also built the latest fontconfig from source. Another dead end.

[We are using an Amazon-provided Ubuntu image](https://github.com/web-platform-tests/results-collection/blob/ae0364bed7da3d6604e9418e1633e18ca3383e41/provisioning/infrastructure/variables.tf#L63-L75), and I finally recognized that the issue may be related to how that was packaged. That was enough for DuckDuckGo to point me to an explanation and a fix: [Font break on AWS EC2 instance](https://github.com/ioi/translation/issues/4). The fix is in `master` at ba828f08f38e1476c439b60c9ba2a260e3f3b72c

This never effected Chrome; my best guess is that browser uses its own internal font matching heuristics.

**Closed by jugglinmike** 2018-10-15 16:15 UTC
